# Generated by Django 3.2.5 on 2021-07-04 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mazeinfo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mazeinfo',
            name='title',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
